version: "3.7"
services:
  Kaddem:
    container_name: Kaddem
    image: neji123/kaddem-1
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbmysql:3306/kaddem?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    restart: always
    depends_on:
      - dbmysql
    networks:
      - my_network

  dbmysql:
    image: "mysql:5.6"
    container_name: dbmysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - my_network



volumes:
  db:

networks:
  my_network: